// Test-only helper: a complete Lead with sensible defaults, overridable per-test.
import type { Lead } from "./types";

export function makeLead(overrides: Partial<Lead> = {}): Lead {
  const base: Lead = {
    id: "lead_test",
    googlePlaceId: "place_1",
    businessName: "Taylor Family Dental",
    normalizedName: "taylor family dental",
    industry: "Dental practice",
    normalizedCategory: "dentist",
    categoryGroup: "Health and Wellness",
    address: "123 Main St",
    city: "Pasadena",
    state: "CA",
    postalCode: "91101",
    latitude: null,
    longitude: null,
    phone: "2135550100",
    website: "https://taylordental.com",
    websiteDomain: "taylordental.com",
    publicEmail: "hello@taylordental.com",
    contactFormUrl: null,
    socialLinks: [],
    locationsCount: 1,
    rating: 4.7,
    reviewCount: 180,
    businessStatus: "OPERATIONAL",
    googleMapsUrl: "https://maps.google.com/?cid=1",
    hours: null,
    source: "Google Places",
    retrievedAt: null,
    tier: null,
    leadScore: null,
    scoreBreakdown: null,
    pipelineStage: "Discovered",
    estimatedValueLow: 8000,
    estimatedValueHigh: 18000,
    recommendedService: null,
    recommendedAction: null,
    recommendationReason: null,
    opportunitySummary: null,
    strengths: [],
    acquisitionStrategy: null,
    acquisitionScore: null,
    acquisitionReason: null,
    acquisitionScoreBreakdown: null,
    acquisitionOverride: false,
    assignedTo: "jordan", assignedAt: null, assignmentReason: null, lastOperatorActivityAt: null,
    note: null,
    lastContactAt: null,
    nextFollowUpAt: null,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  };
  return { ...base, ...overrides };
}
