// ─────────────────────────────────────────────────────────────────────────────
// THE ONE CANONICAL "MAY THIS COMPANY ENTER AUTOMATIC NEW-OUTREACH PREPARATION?" SELECTOR.
//
// A single, pure predicate shared by every surface that decides whether a lead may be automatically
// (re)prepared for NEW outreach — the deep-recapture cron, the fresh-inventory prep orchestrator, the
// Today background-status count, and the Content Studio focused queue. Because there is exactly ONE rule,
// "being reanalyzed" can never silently include a company that is already committed, contacted, or done.
//
// A company is eligible for automatic preparation / deep recapture ONLY when it is ALL of:
//   • not internal / not a test lead
//   • not in a terminal pipeline stage (still commercially eligible for new outreach)
//   • uncontacted            — we never re-prepare a business already in an outreach sequence
//   • unscheduled            — a scheduled binding is a committed send; never disturb it
//   • not suppressed/unsubscribed/bounced
//   • not already represented by an ASSEMBLED or FROZEN package (READY_TO_APPROVE|FROZEN|SCHEDULED|SENT)
//     — an INCOMPLETE draft is still "awaiting only voiceover" and MAY be recaptured/regenerated
//   • equipped with a valid website AND a valid public recipient
//
// The verdict carries the SINGLE most-specific ineligibility reason so the operator "reconcile" table can
// classify each company exactly (Scheduled / Contacted / Already assembled / Automatically excluded).
// Pure + dependency-injected: callers pass already-computed signals; this file never touches the DB.
// ─────────────────────────────────────────────────────────────────────────────
import type { ProspectPackageState } from "./prospect-package";

export type PrepIneligibilityReason =
  | "internal"
  | "terminal-stage"
  | "suppressed"
  | "scheduled"
  | "assembled-package"
  | "contacted"
  | "no-website"
  | "no-recipient";

export interface PrepEligibilityInput {
  internal: boolean;
  pipelineStage: string;
  terminal: boolean;
  contacted: boolean;
  scheduled: boolean;
  suppressed: boolean;
  hasWebsite: boolean;
  recipientValid: boolean;
  /** Latest prospect-package state for the lead, or null if none has ever been assembled. */
  packageState: ProspectPackageState | null;
}

export interface PrepEligibilityVerdict {
  eligible: boolean;
  reason: PrepIneligibilityReason | null;
}

/** A package that already carries a committed/assembled artifact — re-preparing would either duplicate it
 *  or disturb a send. INCOMPLETE is deliberately absent: it is a draft awaiting only the voiceover and may
 *  be regenerated by recapture. */
const ASSEMBLED_STATES: ReadonlySet<ProspectPackageState> = new Set(["READY_TO_APPROVE", "FROZEN", "SCHEDULED", "SENT"]);

export function isAssembledPackageState(state: ProspectPackageState | null | undefined): boolean {
  return !!state && ASSEMBLED_STATES.has(state);
}

/**
 * THE canonical gate. Reason precedence is chosen so the most decisive commitment wins the label:
 *   internal → terminal → suppressed → scheduled → assembled-package → contacted → no-website → no-recipient.
 * (A lead that is BOTH contacted and already-assembled reports "assembled-package"; a lead that is BOTH
 *  scheduled and contacted reports "scheduled" — the stronger commitment.)
 */
export function reanalysisEligibility(i: PrepEligibilityInput): PrepEligibilityVerdict {
  if (i.internal) return { eligible: false, reason: "internal" };
  if (i.terminal) return { eligible: false, reason: "terminal-stage" };
  if (i.suppressed) return { eligible: false, reason: "suppressed" };
  if (i.scheduled) return { eligible: false, reason: "scheduled" };
  if (isAssembledPackageState(i.packageState)) return { eligible: false, reason: "assembled-package" };
  if (i.contacted) return { eligible: false, reason: "contacted" };
  if (!i.hasWebsite) return { eligible: false, reason: "no-website" };
  if (!i.recipientValid) return { eligible: false, reason: "no-recipient" };
  return { eligible: true, reason: null };
}

/** Plain-language classification for the "reconcile the nine" operator table (mandate part 2). */
export const PREP_INELIGIBILITY_LABEL: Record<PrepIneligibilityReason, string> = {
  "internal": "Internal / test — excluded",
  "terminal-stage": "Terminal stage — excluded",
  "suppressed": "Suppressed / unsubscribed — excluded",
  "scheduled": "Scheduled — no reanalysis",
  "assembled-package": "Already assembled — no reanalysis",
  "contacted": "Contacted — no reanalysis",
  "no-website": "No usable website — excluded",
  "no-recipient": "No usable recipient — excluded",
};

export function classifyPrep(v: PrepEligibilityVerdict): string {
  return v.eligible ? "Eligible for deep recapture" : PREP_INELIGIBILITY_LABEL[v.reason!];
}
