// ─────────────────────────────────────────────────────────────────────────────
// CONTENT STUDIO + MEDIA ACTION MANIFEST (mandate 23). The canonical, machine-checkable registry of every
// interactive Content Studio / media control. Breakbot/CI fails if a Studio/media control ships without a
// registered action ID + acceptance scenario here (see studio-manifest.test.ts + the media journeys).
// ─────────────────────────────────────────────────────────────────────────────
export interface StudioActionSpec {
  id: string;
  surface: string;
  precondition: string;
  goal: string;
  expectedUi: string;
  expectedPersisted: string;
  queueCount: string;
  audit: string;
  sideEffect: "none" | "render" | "provider";  // render/provider side-effect allowance
  deterministicTest: string;
  syntheticJourney: string;
  domMarker: string | null;
}

export const STUDIO_ACTIONS: StudioActionSpec[] = [
  { id: "studio.open", surface: "/company/[leadId]", precondition: "a company with video work", goal: "open the video workspace", expectedUi: "Full Package / studio view", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: null },
  { id: "studio.filter-needs-narration", surface: "/queue/voiceover", precondition: "Today", goal: "see companies needing narration", expectedUi: "needs-narration list; count==list", queueCount: "count equals list", expectedPersisted: "none", audit: "none", sideEffect: "none", deterministicTest: "breakbot-scheduled-journey", syntheticJourney: "media-goal", domMarker: "[data-queue-list]" },
  { id: "studio.filter-rendering", surface: "/queue/rendering", precondition: "Today", goal: "see rendering companies", expectedUi: "rendering list; count==list", queueCount: "count equals list", expectedPersisted: "none", audit: "none", sideEffect: "none", deterministicTest: "breakbot-scheduled-journey", syntheticJourney: "media-goal", domMarker: "[data-queue-list]" },
  { id: "studio.open-company", surface: "/company/[leadId]", precondition: "queue open", goal: "open a company's video", expectedUi: "package-aware detail", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: "[data-fullpackage-video]" },
  { id: "studio.preview-video", surface: "/company/[leadId]", precondition: "canonical video available", goal: "preview the current video (incl. pre-narration base)", expectedUi: "operator player opens with a video element", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: "[data-operator-preview-open]" },
  { id: "studio.preview-video-element", surface: "player", precondition: "preview open", goal: "watch the canonical video", expectedUi: "video element streams operator route", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: "[data-operator-preview-video]" },
  { id: "studio.close-preview", surface: "player", precondition: "preview open", goal: "close the player (X)", expectedUi: "player closes; focus returns; no state change", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: "[data-operator-preview-close]" },
  { id: "studio.back-preview", surface: "player", precondition: "preview open", goal: "go back from the player", expectedUi: "player closes to the workspace", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: "[data-operator-preview-back]" },
  { id: "studio.escape-preview", surface: "player", precondition: "preview open", goal: "close with Escape (desktop)", expectedUi: "player closes", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: null },
  { id: "studio.download", surface: "player", precondition: "canonical video available", goal: "download the completed video", expectedUi: "Blob download (no raw nav); correct filename", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: "[data-operator-preview-download]" },
  { id: "studio.upload-narration", surface: "/company/[leadId]", precondition: "needs narration", goal: "upload a voiceover", expectedUi: "upload accepted; company moves to Rendering", expectedPersisted: "upload + queued render job", queueCount: "needs-narration → rendering", audit: "none", sideEffect: "render", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: null },
  { id: "studio.observe-rendering", surface: "/company/[leadId]", precondition: "render queued/running", goal: "observe honest render status", expectedUi: "queued/rendering state; terminal failure never spins", expectedPersisted: "job status truth", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: null },
  { id: "studio.retry-failed-render", surface: "/company/[leadId]", precondition: "render failed (retryable)", goal: "retry a failed render", expectedUi: "retry offered; not an endless spinner", expectedPersisted: "re-queued job", queueCount: "unchanged", audit: "none", sideEffect: "render", deterministicTest: "render-lifecycle.test", syntheticJourney: "media-goal", domMarker: null },
  { id: "studio.preview-completed", surface: "/company/[leadId]", precondition: "render ready", goal: "preview the finished canonical video", expectedUi: "operator player shows the ready artifact", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: "[data-operator-preview-open]" },
  { id: "studio.reject", surface: "/company/[leadId]", precondition: "any", goal: "reject / stop future outreach", expectedUi: "reason panel → confirm; leaves pipeline", expectedPersisted: "pipelineStage Rejected", queueCount: "count decremented", audit: "lead.rejected", sideEffect: "none", deterministicTest: "breakbot-reject-journey", syntheticJourney: "media-goal", domMarker: "[data-reject-control]" },
  { id: "studio.return-today", surface: "/company/[leadId]", precondition: "detail open", goal: "return to Today", expectedUi: "Today loads", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: "[data-nav-close]" },
  { id: "studio.missing-artifact", surface: "/company/[leadId]", precondition: "video artifact missing", goal: "understand the video is unavailable", expectedUi: "preview offered as unavailable + reason (not a broken player)", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-media-journey", syntheticJourney: "media-goal", domMarker: "[data-operator-preview-unavailable]" },

  // ── Mandate 25: two-tab Content Studio + expand-and-personalize controls ──────────────────────────────
  { id: "studio.tab-proposal", surface: "/content-studio?type=proposal", precondition: "studio open", goal: "switch to Proposal Videos", expectedUi: "proposal workspace; count==list; URL ?type=proposal", expectedPersisted: "none", queueCount: "proposal count equals its lists", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-studio-tab]" },
  { id: "studio.tab-content", surface: "/content-studio?type=content", precondition: "studio open", goal: "switch to Content Videos", expectedUi: "content workspace; count==list; URL ?type=content", expectedPersisted: "none", queueCount: "content count equals its lists", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-studio-tab]" },
  { id: "studio.tab-back-refresh", surface: "/content-studio", precondition: "a tab selected", goal: "refresh / browser Back preserves the tab", expectedUi: "same tab + filter after refresh/Back", expectedPersisted: "none (URL state)", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: null },
  { id: "studio.workspace-group", surface: "/content-studio", precondition: "a tab selected", goal: "read videos grouped by canonical state", expectedUi: "group sections; each count equals its cards", expectedPersisted: "none", queueCount: "group count equals cards", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-workspace-group]" },
  { id: "studio.workspace-empty", surface: "/content-studio", precondition: "a tab with no videos", goal: "see an honest empty state", expectedUi: "empty-state message (not a broken list)", expectedPersisted: "none", queueCount: "0", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-workspace-empty]" },
  { id: "studio.select-card", surface: "/content-studio", precondition: "a tab with videos", goal: "open a video's detail", expectedUi: "detail for the selected card (same tab)", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-workspace-card]" },
  { id: "studio.inspect-quality", surface: "/content-studio", precondition: "a proposal card", goal: "read the narration quality classification + reasons", expectedUi: "quality badge + reasons", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-proposal-quality]" },
  { id: "studio.resolve-ambiguous", surface: "/content-studio", precondition: "unclassified videos exist", goal: "surface unclassified videos to resolve before use", expectedUi: "unclassified indicator (barred from both tabs)", expectedPersisted: "none", queueCount: "unclassified count", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-tab-unclassified]" },
  { id: "studio.expand-open", surface: "proposal detail", precondition: "a proposal video", goal: "open expand-and-personalize", expectedUi: "panel opens; current quality analyzed", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-open]" },
  { id: "studio.expand-run", surface: "expand panel", precondition: "panel open + evidence", goal: "expand from company evidence", expectedUi: "proposed draft grounded in evidence ids; blocker if insufficient", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-run]" },
  { id: "studio.expand-compare", surface: "expand panel", precondition: "a proposed draft", goal: "compare original vs proposed", expectedUi: "side-by-side + word counts + duration + quality", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-compare]" },
  { id: "studio.expand-edit", surface: "expand panel", precondition: "a proposed draft", goal: "edit the proposed draft", expectedUi: "editable textarea; live word count", expectedPersisted: "none (until accept)", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-edit]" },
  { id: "studio.expand-regenerate", surface: "expand panel", precondition: "a proposed draft", goal: "regenerate the draft", expectedUi: "a fresh evidence-grounded draft", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-regenerate]" },
  { id: "studio.expand-accept", surface: "expand panel", precondition: "a non-frozen, non-approved draft w/o unsupported claims", goal: "accept as a new revision", expectedUi: "revision N; existing audio/render outdated; needs new upload+render", expectedPersisted: "new narration revision; approval cleared", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-accept]" },
  { id: "studio.expand-cancel", surface: "expand panel", precondition: "a proposed draft", goal: "cancel without mutating", expectedUi: "draft discarded; nothing persisted", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-cancel]" },
  { id: "studio.upload-replacement-narration", surface: "proposal detail", precondition: "revision accepted (audio outdated)", goal: "upload new narration audio for the new script", expectedUi: "upload accepted; company re-enters Rendering", expectedPersisted: "upload + queued render job (new input version)", queueCount: "→ rendering", audit: "none", sideEffect: "render", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: null },
  { id: "studio.rerender-after-revision", surface: "proposal detail", precondition: "new script + new audio", goal: "render the revised script", expectedUi: "new render; a stale prior render can never become canonical", expectedPersisted: "new render job for the new input version", queueCount: "unchanged", audit: "none", sideEffect: "render", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: null },

  // ── Mandate 26: mobile full-page workspaces + truthful state-specific narration actions ───────────────
  { id: "studio.card-deeplink", surface: "/content-studio (mobile)", precondition: "a tab with videos", goal: "tap a company card → dedicated full-page workspace", expectedUi: "navigates to /content-studio/[purpose]/[leadId]; survives refresh + Back", expectedPersisted: "none (URL state)", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-studio-mobile-journey", syntheticJourney: "studio-mobile-goal", domMarker: "[data-workspace-href]" },
  { id: "studio.cs-back", surface: "/content-studio/[purpose]/[leadId]", precondition: "dedicated workspace open", goal: "return to the originating tab/filter", expectedUi: "back to the exact ?type= list it came from", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-studio-mobile-journey", syntheticJourney: "studio-mobile-goal", domMarker: "[data-cs-back]" },
  { id: "studio.cs-prev", surface: "/content-studio/[purpose]/[leadId]", precondition: "not the first card", goal: "go to the previous company in the tab", expectedUi: "prev company workspace (real tab ordering); disabled at edge", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-studio-mobile-journey", syntheticJourney: "studio-mobile-goal", domMarker: "[data-cs-prev]" },
  { id: "studio.cs-next", surface: "/content-studio/[purpose]/[leadId]", precondition: "not the last card", goal: "go to the next company in the tab", expectedUi: "next company workspace (real tab ordering); disabled at edge", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-studio-mobile-journey", syntheticJourney: "studio-mobile-goal", domMarker: "[data-cs-next]" },
  { id: "studio.expand-permissions", surface: "expand panel", precondition: "panel open", goal: "read the truthful state-specific allowance", expectedUi: "headline + detail: what's allowed here and why (editable vs committed-fork)", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-permissions]" },
  { id: "studio.expand-create-improved-version", surface: "expand panel (committed package)", precondition: "FROZEN/SCHEDULED/SENT package", goal: "fork a NEW unapproved draft without touching the frozen package", expectedUi: "Create improved version; frozen bytes + binding unchanged; needs new approval+audio+render", expectedPersisted: "new draft revision; frozen package + binding untouched", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-fork]" },
  { id: "studio.expand-no-safe-alternative", surface: "expand panel", precondition: "regenerated past the distinct-variant set", goal: "honestly report no materially different draft", expectedUi: "no-safe-alternative note (never a silent repeat)", expectedPersisted: "none", queueCount: "unchanged", audit: "none", sideEffect: "none", deterministicTest: "breakbot-videos-journey", syntheticJourney: "videos-goal", domMarker: "[data-expand-regen-note]" },
];

export function studioActionIds(): string[] { return STUDIO_ACTIONS.map((a) => a.id); }
