// ─────────────────────────────────────────────────────────────────────────────
// ONE ROLE CHANGE: promote Alex from the prose role "Operator" to the canonical
// role "head_of_outreach", so the declared operating model — Jordan and Alex as
// CO-EQUAL outreach managers — is what the deployed system actually enforces.
//
// This is NOT an ownership change. No lead moves. No email is sent. No
// environment variable changes. It writes exactly two rows:
//
//   1. users.role for `alex`         "Operator" -> "head_of_outreach"
//   2. one append-only audit_log entry (action = operator.role)
//
// BOTH IN ONE TRANSACTION. An earlier version of this script ran them as two
// separate statements and the second failed — audit_log.id has no database
// default, it is generated by the application — leaving the role changed with no
// audit trail. A role change that is not recorded is worse than one that did not
// happen, so the two writes are now atomic: either the workspace has a new Head
// of Outreach AND the record of who made him one, or it has neither.
//
// Idempotent: re-running after the change writes nothing.
//
//   railway run --service Postgres -- ./node_modules/.bin/tsx scripts/set-alex-head-of-outreach.ts
// ─────────────────────────────────────────────────────────────────────────────
import "./loadEnv";

if (process.env.DATABASE_PUBLIC_URL && process.env.DATABASE_URL?.includes(".railway.internal")) {
  process.env.DATABASE_URL = process.env.DATABASE_PUBLIC_URL;
}

const TARGET = "alex";
const ACTOR = "jordan";
const NEW_ROLE = "head_of_outreach";
const REASON = "Co-equal outreach managers until the first three paying clients.";

async function main() {
  const { newId } = await import("../src/lib/store");
  const postgres = (await import("postgres")).default;
  const url = process.env.DATABASE_URL!;
  const sql = postgres(url, {
    max: 1,
    prepare: false,
    ssl: url.includes("proxy.rlwy.net") ? { rejectUnauthorized: false } : ("require" as const),
  });

  try {
    const [before] = await sql`select id, role from users where id = ${TARGET}`;
    if (!before) { console.log(`No operator '${TARGET}'. Nothing written.`); return; }
    console.log(`before: ${before.id} role=${JSON.stringify(before.role)}`);

    // Has the audit entry already been written for the current value?
    const [logged] = await sql`
      select count(*)::int c from audit_log
      where action = 'operator.role' and target_id = ${TARGET} and meta->>'to' = ${NEW_ROLE}`;

    if (before.role === NEW_ROLE && Number(logged.c) > 0) {
      console.log("Already Head of Outreach, and the change is on the record. Nothing written.");
      return;
    }

    const now = new Date().toISOString();

    await sql.begin(async (tx) => {
      if (before.role !== NEW_ROLE) {
        await tx`update users set role = ${NEW_ROLE}, updated_at = ${now} where id = ${TARGET}`;
      }
      if (Number(logged.c) === 0) {
        await tx`
          insert into audit_log (id, action, actor, target_type, target_id, meta, ip, created_at)
          values (${newId("audit")}, 'operator.role', ${ACTOR}, 'operator', ${TARGET},
                  ${tx.json({ from: before.role, to: NEW_ROLE, label: "Head of Outreach", reason: REASON })},
                  null, ${now})`;
      }
    });

    const [after] = await sql`select id, role from users where id = ${TARGET}`;
    const [entries] = await sql`
      select count(*)::int c from audit_log where action = 'operator.role' and target_id = ${TARGET}`;
    console.log(`after:  ${after.id} role=${JSON.stringify(after.role)}`);
    console.log(`operator.role audit entries for ${TARGET}: ${entries.c}`);
    console.log("No ownership touched. No lead moved. No email sent.");
  } finally {
    await sql.end({ timeout: 5 });
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
